import os

MONGODB_URI = os.getenv("MONGODB_URI")

CAPTCHA_SITE_KEY = os.getenv("CAPTCHA_SITE_KEY")
CAPTCHA_SECRET_KEY = os.getenv("CAPTCHA_SECRET_KEY")

STRIPE_PUBLIC_KEY = os.getenv("STRIPE_PUBLIC_KEY")
STRIPE_SECRET_KEY = os.getenv("STRIPE_SECRET_KEY")

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
IP_API_KEY = os.getenv("IP_API_KEY")
